module.exports = [
  {
    title: "The Godfather",
    year: "1972",
    rated: "R",
    released: "24 Mar 1972",
    runtime: "175 min",
    genre: "Crime, Drama",
    director: "Francis Ford Coppola",
    writer: "Mario Puzo, Francis Ford Coppola",
    actors: "Marlon Brando, Al Pacino, James Caan",
    plot: "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
    country: "United States",
    awards: "Won 3 Oscars. 32 wins & 31 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",

    imdbRating: "9.2",
    imdbVotes: "1,910,007",
    imdbID: "tt0068646",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    year: "1977",
    rated: "PG",
    released: "25 May 1977",
    runtime: "121 min",
    genre: "Action, Adventure, Fantasy",
    director: "George Lucas",
    writer: "George Lucas",
    actors: "Mark Hamill, Harrison Ford, Carrie Fisher",
    plot: "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.",
    country: "United States",
    awards: "Won 6 Oscars. 65 wins & 31 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg",

    imdbRating: "8.6",
    imdbID: "tt0076759",
  },
  {
    title: "Donnie Darko",
    year: "2001",
    rated: "R",
    released: "19 Jan 2001",
    runtime: "113 min",
    genre: "Drama, Mystery, Sci-Fi",
    director: "Richard Kelly",
    writer: "Richard Kelly",
    actors: "Jake Gyllenhaal, Jena Malone, Mary McDonnell",
    plot: "Donnie Darko doesn't get along too well with his family, his teachers, and his classmates; but he does manage to find a sympathetic friend in Gretchen, who agrees to date him. He has a compassionate psychiatrist, who discovers hypnosis is the means to unlock hidden secrets. His other companion may not be a true ally. Donnie has a friend named Frank, a large bunny which only Donnie can see. When an engine falls off a plane and destroys his bedroom, Donnie is not there. Both the event, and Donnie's escape, seem to have been caused by supernatural events.",
    country: "United States",
    awards: "12 wins & 16 nominations",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjZlZDlkYTktMmU1My00ZDBiLWFlNjEtYTBhNjVhOTM4ZjJjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",

    imdbRating: "8.0",
    imdbID: "tt0246578",
  },
  {
    title: "The Shawshank Redemption",
    year: "1994",
    rated: "R",
    released: "14 Oct 1994",
    runtime: "142 min",
    genre: "Drama",
    director: "Frank Darabont",
    writer: "Stephen King, Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    plot: "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
    country: "United States",
    awards: "Nominated for 7 Oscars. 21 wins & 43 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",

    imdbRating: "9.3",
    imdbID: "tt0111161",
  },
  {
    title: "12 years a Slave",
    year: "2013",
    rated: "R",
    released: "08 Nov 2013",
    runtime: "134 min",
    genre: "Biography, Drama, History",
    director: "Steve McQueen",
    writer: "John Ridley, Solomon Northup",
    actors: "Chiwetel Ejiofor, Michael Kenneth Williams, Michael Fassbender",
    plot: "Based on an incredible true story of one man's fight for survival and freedom. In the pre-Civil War United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery. Facing cruelty personified by a malevolent slave owner, as well as unexpected kindnesses, Solomon struggles not only to stay alive, but to retain his dignity. In the twelfth year of his unforgettable odyssey, Solomon's chance meeting with a Canadian abolitionist will forever alter his life.",
    country: "United States, United Kingdom",
    awards: "Won 3 Oscars. 242 wins & 337 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_SX300.jpg",

    imdbRating: "8.1",
    imdbID: "tt2024544",
  },
  {
    title: "Spider-Man 2",
    year: "2004",
    rated: "PG-13",
    released: "30 Jun 2004",
    runtime: "127 min",
    genre: "Action, Adventure, Sci-Fi",
    director: "Sam Raimi",
    writer: "Stan Lee, Steve Ditko, Alfred Gough",
    actors: "Tobey Maguire, Kirsten Dunst, Alfred Molina",
    plot: "Peter Parker is an unhappy man: after two years of fighting crime as Spider-Man, his life has begun to fall apart. The girl he loves is engaged to someone else, his grades are slipping, he cannot keep any of his jobs, and on top of it, the newspaper Daily Bugle is attacking him viciously, claiming that Spider-Man is a criminal. He reaches the breaking point and gives up the crime fighter's life, once and for all. But after a failed fusion experiment, eccentric and obsessive scientist Dr. Otto Octavius is transformed into super villain Doctor Octopus, Doc Ock for short, having four long tentacles as extra hands. Peter guesses it might just be time for Spider-Man to return, but would he act upon it?",
    country: "United States",
    awards: "Won 1 Oscar. 25 wins & 60 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMzY2ODk4NmUtOTVmNi00ZTdkLTlmOWYtMmE2OWVhNTU2OTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",

    imdbRating: "7.4",
    imdbID: "tt0316654",
  },
  {
    title: "Batman Begins",
    year: "2005",
    rated: "PG-13",
    released: "15 Jun 2005",
    runtime: "140 min",
    genre: "Action, Crime, Drama",
    director: "Christopher Nolan",
    writer: "Bob Kane, David S. Goyer, Christopher Nolan",
    actors: "Christian Bale, Michael Caine, Ken Watanabe",
    plot: "When his parents are killed, billionaire playboy Bruce Wayne relocates to Asia, where he is mentored by Henri Ducard and Ra's Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as \"Batman\". But it doesn't stay quiet for long.",
    country: "United States, United Kingdom",
    awards: "Nominated for 1 Oscar. 14 wins & 79 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    imdbRating: "8.2",
    imdbID: "tt0372784",
  },
  {
    title: "Blade Runner",
    year: "1982",
    rated: "R",
    released: "25 Jun 1982",
    runtime: "117 min",
    genre: "Action, Drama, Sci-Fi",
    director: "Ridley Scott",
    writer: "Hampton Fancher, David Webb Peoples, Philip K. Dick",
    actors: "Harrison Ford, Rutger Hauer, Sean Young",
    plot: 'In the early twenty-first century, the Tyrell Corporation, during what was called the Nexus phase, developed robots, called "replicants", that were supposed to aid society, the replicants which looked and acted like humans. When the superhuman generation Nexus 6 replicants, used for dangerous off-Earth endeavors, began a mutiny on an off-Earth colony, replicants became illegal on Earth. Police units, called "blade runners", have the job of destroying - or in their parlance "retiring" - any replicant that makes its way back to or created on Earth, with anyone convicted of aiding or assisting a replicant being sentenced to death. It\'s now November, 2019 in Los Angeles, California. Rick Deckard, a former blade runner, is called out of retirement when four known replicants, most combat models, have made their way back to Earth, with their leader being Roy Batty. One, Leon Kowalski, tried to infiltrate his way into the Tyrell Corporation as an employee, but has since been able to escape. Beyond following Leon\'s trail in hopes of finding and retiring them all, Deckard believes part of what will help him is figuring out what the replicants wanted with the Tyrell Corporation in trying to infiltrate it. The answer may lie with Tyrell\'s fail-safe backup mechanism. Beyond tracking the four, Deckard faces a possible dilemma in encountering a fifth replicant: Rachael, who works as Tyrell\'s assistant. The issue is that Dr. Elden Tyrell is experimenting with her, to provide her with fake memories so as to be able to better control her. With those memories, Rachael has no idea that she is not human. The problem is not only Rachael\'s assistance to Deckard, but that he is beginning to develop feelings for her.',
    country: "United States",
    awards: "Nominated for 2 Oscars. 13 wins & 19 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",

    imdbRating: "8.1",
    imdbID: "tt0083658",
  },
];
