const shows = require("./shows");

const date = (days) => {
  const movieDate = new Date();
  movieDate.setDate(movieDate.getDate() + days);
  return movieDate;
};

module.exports = [
  {
    title: "Inception",
    year: "2010",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/12A_shupya.png",
    released: "16 Jul 2010",
    runtime: "148 mins",
    genre: "Action, Adventure, Sci-Fi",
    director: "Christopher Nolan",
    writer: "Christopher Nolan",
    actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    plot: "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
    country: "United States, United Kingdom",
    awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    imdbRating: "8.8",
    imdbID: "tt1375666",
    shows: shows,
  },
  {
    title: "The Dark Knight",
    year: "2008",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/12A_shupya.png",
    released: "18 Jul 2008",
    runtime: "152 mins",
    genre: "Action, Crime, Drama",
    director: "Christopher Nolan",
    writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    plot: 'Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as "The Joker" appears in Gotham, creating a new wave of chaos. Batman\'s struggle against The Joker becomes deeply personal, forcing him to "confront everything he believes" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.',
    country: "United States, United Kingdom",
    awards: "Won 2 Oscars. 162 wins & 163 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    imdbRating: "9.0",
    imdbID: "tt0468569",
    shows: shows,
  },

  {
    title: "Pulp Fiction",
    year: "1994",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "14 Oct 1994",
    runtime: "154 mins",
    genre: "Crime, Drama",
    director: "Quentin Tarantino",
    writer: "Quentin Tarantino, Roger Avary",
    actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
    plot: "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
    country: "United States",
    awards: "Won 1 Oscar. 70 wins & 75 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    imdbRating: "8.9",
    imdbID: "tt0110912",
    shows: shows,
  },
  {
    title: "Fight Club",
    year: "1999",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "15 Oct 1999",
    runtime: "139 mins",
    genre: "Drama",
    director: "David Fincher",
    writer: "Chuck Palahniuk, Jim Uhls",
    actors: "Brad Pitt, Edward Norton, Meat Loaf",
    plot: "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power.",
    country: "Germany, United States",
    awards: "Nominated for 1 Oscar. 12 wins & 38 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    imdbRating: "8.8",
    imdbID: "tt0137523",
    shows: shows,
  },
  {
    title: "The Matrix",
    year: "1999",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "31 Mar 1999",
    runtime: "136 mins",
    genre: "Action, Sci-Fi",
    director: "Lana Wachowski, Lilly Wachowski",
    writer: "Lilly Wachowski, Lana Wachowski",
    actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    plot: "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.",
    country: "United States, Australia",
    awards: "Won 4 Oscars. 42 wins & 52 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    imdbRating: "8.7",
    imdbID: "tt0133093",
    shows: shows,
  },
  {
    title: "Interstellar",
    year: "2014",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766380/pg-13_gkz7rg.png",
    released: "07 Nov 2014",
    runtime: "169 mins",
    genre: "Adventure, Drama, Sci-Fi",
    director: "Christopher Nolan",
    writer: "Jonathan Nolan, Christopher Nolan",
    actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    plot: "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
    country: "United States, United Kingdom, Canada",
    awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    imdbRating: "8.7",
    imdbID: "tt0816692",
    shows: shows,
  },
  {
    title: "American Psycho",
    year: "2000",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "14 Apr 2000",
    runtime: "102 mins",
    genre: "Crime, Drama, Horror",
    director: "Mary Harron",
    writer: "Bret Easton Ellis, Mary Harron, Guinevere Turner",
    actors: "Christian Bale, Justin Theroux, Josh Lucas",
    plot: "It's the late 1980s. Twenty-seven year old Wall Streeter Patrick Bateman travels among a closed network of the proverbial beautiful people, that closed network in only they able to allow others like themselves in in a feeling of superiority. Patrick has a routinized morning regimen to maintain his appearance of attractiveness and fitness. He, like those in his network, are vain, narcissistic, egomaniacal and competitive, always having to one up everyone else in that presentation of oneself, but he, unlike the others, realizes that, for himself, all of these are masks to hide what is truly underneath, someone/something inhuman in nature. In other words, he is comprised of a shell resembling a human that contains only greed and disgust, greed in wanting what others may have, and disgust for those who do not meet his expectations and for himself in not being the first or the best. That disgust ends up manifesting itself in wanting to rid the world of those people, he not seeing them as people but only of those characteristics he wants to rid.",
    country: "United States, Canada",
    awards: "8 wins & 13 nominations",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZTM2ZGJmNjQtN2UyOS00NjcxLWFjMDktMDE2NzMyNTZlZTBiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    imdbRating: "7.6",
    imdbID: "tt0144084",
    shows: shows,
  },
  {
    title: "Trainspotting",
    year: "1996",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "09 Aug 1996",
    runtime: "93 mins",
    genre: "Drama",
    director: "Danny Boyle",
    writer: "Irvine Welsh, John Hodge",
    actors: "Ewan McGregor, Ewen Bremner, Jonny Lee Miller",
    plot: "A wild, freeform, Rabelaisian trip through the darkest recesses of Edinburgh low-life, focusing on Mark Renton and his attempt to give up his heroin habit, and how the latter affects his relationship with family and friends: Sean Connery wannabe Sick Boy, dimbulb Spud, psycho Begbie, 14-year-old girlfriend Diane, and clean-cut athlete Tommy, who's never touched drugs but can't help being curious about them...",
    country: "United Kingdom",
    awards: "Nominated for 1 Oscar. 23 wins & 35 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMzA5Zjc3ZTMtMmU5YS00YTMwLWI4MWUtYTU0YTVmNjVmODZhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    imdbRating: "8.1",
    imdbID: "tt0117951",
    shows: shows,
  },
  {
    title: "The Departed",
    year: "2006",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "06 Oct 2006",
    runtime: "151 mins",
    genre: "Crime, Drama, Thriller",
    director: "Martin Scorsese",
    writer: "William Monahan, Alan Mak, Felix Chong",
    actors: "Leonardo DiCaprio, Matt Damon, Jack Nicholson",
    plot: "In this crime-action tour de force, the South Boston state police force is waging war on Irish-American organized crime. Young undercover cop Billy Costigan is assigned to infiltrate the mob syndicate run by gangland chief Frank Costello. While Billy quickly gains Costello's confidence, Colin Sullivan, a hardened young criminal who has infiltrated the state police as an informer for the syndicate is rising to a position of power in the Special Investigation Unit. Each man becomes deeply consumed by their double lives, gathering information about the plans and counter-plans of the operations they have penetrated. But when it becomes clear to both the mob and the police that there is a mole in their midst, Billy and Colin are suddenly in danger of being caught and exposed to the enemy - and each must race to uncover the identity of the other man in time to save themselves. But is either willing to turn on their friends and comrades they've made during their long stints undercover?",
    country: "United States, Hong Kong",
    awards: "Won 4 Oscars. 98 wins & 141 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
    imdbRating: "8.5",
    imdbID: "tt0407887",
    shows: shows,
  },
  {
    title: "The Wolf of Wall Street",
    year: "2013",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "25 Dec 2013",
    runtime: "180 mins",
    genre: "Biography, Comedy, Crime",
    director: "Martin Scorsese",
    writer: "Terence Winter, Jordan Belfort",
    actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
    plot: 'In the early 1990s, Jordan Belfort teamed with his partner Donny Azoff and started brokerage firm Stratton Oakmont. Their company quickly grows from a staff of 20 to a staff of more than 250 and their status in the trading community and Wall Street grows exponentially. So much that companies file their initial public offerings through them. As their status grows, so do the amount of substances they abuse, and so do their lies. They draw attention like no other, throwing lavish parties for their staff when they hit the jackpot on high trades. That ultimately leads to Belfort featured on the cover of Forbes Magazine, being called "The Wolf Of Wall St.". With the FBI onto Belfort\'s trading schemes, he devises new ways to cover his tracks and watch his fortune grow. Belfort ultimately comes up with a scheme to stash their cash in a European bank. But with the FBI watching him like a hawk, how long will Belfort and Azoff be able to maintain their elaborate wealth and luxurious lifestyles?',
    country: "United States",
    awards: "Nominated for 5 Oscars. 37 wins & 179 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    imdbRating: "8.2",
    imdbID: "tt0993846",
    shows: shows,
  },
  {
    title: "Django Unchained",
    year: "2012",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766702/18_odndxr.png",
    released: "25 Dec 2012",
    runtime: "165 mins",
    genre: "Drama, Western",
    director: "Quentin Tarantino",
    writer: "Quentin Tarantino",
    actors: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
    plot: "In 1858, a bounty-hunter named King Schultz seeks out a slave named Django and buys him because he needs him to find some men he is looking for. After finding them, Django wants to find his wife, Broomhilda, who along with him were sold separately by his former owner for trying to escape. Schultz offers to help him if he chooses to stay with him and be his partner. Eventually they learn that she was sold to a plantation in Mississippi. Knowing they can't just go in and say they want her, they come up with a plan so that the owner will welcome them into his home and they can find a way.",
    country: "United States",
    awards: "Won 2 Oscars. 58 wins & 158 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
    imdbRating: "8.4",
    imdbID: "tt1853728",
    shows: shows,
  },
  {
    title: "Avengers: Infinity War",
    year: "2018",
    rated:
      "https://res.cloudinary.com/dtcoefjmm/image/upload/v1689766380/pg-13_gkz7rg.png",
    released: "27 Apr 2018",
    runtime: "149 mins",
    genre: "Action, Adventure, Sci-Fi",
    director: "Anthony Russo, Joe Russo",
    writer: "Christopher Markus, Stephen McFeely, Stan Lee",
    actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
    plot: "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment, the fate of Earth and existence has never been more uncertain.",
    country: "United States",
    awards: "Nominated for 1 Oscar. 46 wins & 79 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
    imdbRating: "8.4",
    imdbID: "tt4154756",
    shows: shows,
  },
];
